<?php
require_once __DIR__.'/auth.php'; require_once __DIR__.'/../db_connect.php'; require_once __DIR__.'/../provider_client.php';
$providers=fetch_all($conn,"SELECT id,name FROM service_providers WHERE is_active=1 ORDER BY name"); $pid=(int)($_GET['provider_id']??$_POST['provider_id']??0); $items=[];$err='';$msg='';
if($pid){try{$pv=provider_get($pid);$items=provider_services($pv);}catch(Throwable $e){$err=$e->getMessage();}}
if($_SERVER['REQUEST_METHOD']==='POST'&&($_POST['act']??'')==='import'){ $name=trim($_POST['name']??'');$sid=trim($_POST['service_id']??'');$rate=(float)($_POST['rate']??0);$min=max(1,(int)($_POST['min']??1));$max=max($min,(int)($_POST['max']??1000000));$cat=(int)($_POST['category_id']??1);$profit=(float)($_POST['profit_percent']??30);$desc='خدمة موردة تلقائيًا من السيرفر. راجع الوصف والجودة والضمان قبل النشر.';$st=$conn->prepare("INSERT INTO store_services(category_id,name,description,price,currency,is_active,status,service_type,provider_id,provider_service_id,provider_sync_enabled,provider_base_price,provider_price_per,profit_percent,price_mode,min_quantity,max_quantity,quantity_step,show_price,buy_now_enabled) VALUES(?,?,?,0,'EGP',1,'active','supplier',?,?,1,?,1000,?,'provider_auto',?,?,1,1,1)");$st->bind_param('issisddii',$cat,$name,$desc,$pid,$sid,$rate,$profit,$min,$max);$st->execute();$msg='تم استيراد الخدمة. راجع بياناتها قبل النشر.';}
$cats=fetch_all($conn,"SELECT id,name FROM store_categories WHERE is_active=1 ORDER BY sort_order");$page_title_admin='سحب خدمات السيرفرات';include __DIR__.'/layout.php';?>
<?php if($msg):?><div class="alert alert-success"><?= e($msg) ?></div><?php endif;?><?php if($err):?><div class="alert alert-error"><?= e($err) ?></div><?php endif;?>
<div class="panel"><div class="panel-header"><div class="panel-title">⬇️ سحب الخدمات من السيرفر</div></div><form method="get" style="padding:16px;display:flex;gap:8px"><select name="provider_id" class="form-select"><option value="">اختر السيرفر</option><?php foreach($providers as $p):?><option value="<?= $p['id'] ?>" <?= $pid==$p['id']?'selected':'' ?>><?= e($p['name']) ?></option><?php endforeach;?></select><button class="btn btn-primary">سحب الخدمات عبر API</button></form></div>
<?php if($items):?><div class="panel" style="margin-top:16px;overflow:auto"><table class="admin-table"><thead><tr><th>ID</th><th>الخدمة</th><th>Rate / 1000</th><th>Min</th><th>Max</th><th>استيراد</th></tr></thead><tbody><?php foreach($items as $it):?><tr><td><?= e($it['service']??'') ?></td><td><?= e($it['name']??'') ?></td><td><?= e($it['rate']??'') ?></td><td><?= e($it['min']??'') ?></td><td><?= e($it['max']??'') ?></td><td><form method="post" style="display:flex;gap:5px;flex-wrap:wrap"><input type="hidden" name="act" value="import"><input type="hidden" name="provider_id" value="<?= $pid ?>"><input type="hidden" name="service_id" value="<?= e($it['service']??'') ?>"><input type="hidden" name="name" value="<?= e($it['name']??'') ?>"><input type="hidden" name="rate" value="<?= e($it['rate']??0) ?>"><input type="hidden" name="min" value="<?= e($it['min']??1) ?>"><input type="hidden" name="max" value="<?= e($it['max']??1000000) ?>"><select name="category_id" class="form-select" style="width:150px"><?php foreach($cats as $c):?><option value="<?= $c['id'] ?>"><?= e($c['name']) ?></option><?php endforeach;?></select><input name="profit_percent" value="30" type="number" class="form-input" style="width:80px"><button class="btn btn-primary btn-sm">استيراد</button></form></td></tr><?php endforeach;?></tbody></table></div><?php endif;?>
</div></div></div></body></html>